[package]
name = "audio_jack_firmware"
version = "0.1.1"
edition = "2024"
description = "Rust driver for an audio jack and buttons"
license = "MIT OR Apache-2.0"
[dependencies]
xpanse-api = "0.2.3"

embassy-rp = "0.10.0"
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "defmt",
] }

embassy-time = "0.5"
embedded-hal-async = "1.0"